### ISSUE TITLE
Publish to Maven central

### ISSUE THREAD

**Issue by mkurz** [johanandren/sbt-akka-version-check#1]
It seems this library is only hosted on repo.scala-sbt.org which just had a outage: https://github.com/sbt/sbt/issues/7202
I highly recommend publishing a artifacts to maven central via the [sbt-ci-release plugin](https://github.com/sbt/sbt-ci-release) and GitHub actions, see here how this can be done: https://github.com/sbt/sbt-dynver/pull/242

**Comment by mkurz** [comment]
If you need help I could try to set the GH workflow up.

**Comment by johanandren** [comment]
Yep, haven't touched this in four years and forgot I ever created it. I'm not entirely sure anyone is actually using it, but publishing it to maven central would be good. If you have time to pr workflow that would be appreciated, if not I may get around to it "some day".
